### ISSUE TITLE
Cannot setup project

### ISSUE THREAD

**Issue by embarq** [jonsnow123kappa/streamkit-backend#2]
```bash
(venv) embarq@dev:~/projects/streamkit-backend$ pip install -r requirements.txt 
Requirement already satisfied: Flask==0.10.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Flask_SocketIO in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: itsdangerous==0.24 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: Jinja2==2.7.3 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: MarkupSafe==0.23 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: python-engineio in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: python-socketio in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Collecting six==1.9.0 (from -r requirements.txt (line 8))
  Using cached six-1.9.0-py2.py3-none-any.whl
Requirement already satisfied: Werkzeug==0.10.4 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: opencv-python in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: numpy in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Collecting psutil (from -r requirements.txt (line 12))
  Downloading psutil-5.0.1.tar.gz (326kB)
    100% |████████████████████████████████| 327kB 205kB/s 
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/embarq/.cache/pip/wheels/f1/41/93/910ab597b78286fb8685f314a8e9daa9dc35085f5d861589c4
Successfully built psutil
Installing collected packages: six, psutil
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Rolling back uninstall of six
Exception:
Traceback (most recent call last):
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2562, in requires
    dm = self._dep_map
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2809, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2818, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/embarq/projects/streamkit-backend/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/embarq/projects/streamkit-backend/venv/lib/python2.7/site-packages/six-1.10.0.dist-info/METADATA'
```

**Comment by jonsnow123kappa** [comment]
1. `sudo apt-get install python3-dev`
2. `sudo pip3 install virtualenv`
3. `cd streamkit-backend`, `virtualenv venv`
4. `. venv\bin\activate`
5. `(venv)$ pip install -r requirements.txt`
